### ISSUE TITLE
Multiarch isn't working

### ISSUE THREAD

**Issue by xordspar0** [snapcore/core18#129]
I'm trying to build a snap for a 32 bit binary on a 64 bit dev machine. As of https://github.com/snapcore/core18/commit/f87a2341f1059c844a88b38f11d39b2546260820 it should be possible to install 32 bit libraries such as `libstdc++6:i386`, however, i386 doesn't seem to be enabled. If I add a `:i386` packages to `stage-packages` in my snapcraft.yaml, the build step fails and apt recommends that I run `dpkg --add-architecture i386`.

I'm using the current stable core18 snap: `20190409 2019-04-12 (941)`

Here is a minimal snapcraft.yaml that will reproduce it:
```yaml
name: test
version: 0.0.1
summary: test
description: |
  test
grade: devel
confinement: devmode
base: core18
architectures:
  - build-on: amd64
    run-on: [i386, amd64]
parts:
  test-i386:
    plugin: nil
    stage-packages:
      - libstdc++6:i386
```
